name: CI (Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-ubuntu:
    name: CI (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '9.0.100'
      # Need this for Yarn 4.0 (see: https://github.com/actions/setup-node/issues/480#issuecomment-1915448139)
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Restore dependencies
        run: |
          dotnet tool restore
          dotnet paket restore
          yarn install
      - name: Test
        run: ./build.sh -t Test
