name: CI (Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-ubuntu:
    name: CI (Ubuntu)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '6.0'
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: Restore dependencies
      run: |
        dotnet tool restore
        dotnet paket restore
        yarn install
    - name: Build
      run: ./build.sh -t Build
    - name: Test
      run: ./build.sh -t Test
