name: Publish NuGet

on: [workflow_dispatch]

jobs:
  publish:
    name: Publish NuGet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '9.0.100'
      - name: Restore
        run: |
          dotnet tool restore
          dotnet paket restore
      - name: PublishNugetPackages
        env:
          NUGET_PUSH_API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}
        run: ./build.sh -t PublishNugetPackages
